# Production Release Stage Workflow
#
# - **Triggers:** Initiates manually via workflow dispatch with inputs for tag name and run ID.
#
# - **Inputs:**
#   - `tag_name`: The tag name for the release (e.g., v1.0.0).
#   - `run_id`: The ID of the workflow run where the desired download artifact was uploaded from.
#
# - **Permissions:** Requires write-all permission for executing tasks.
#
# - **Jobs:**
#   - **Production Release Stage:**
#     - **Environment:** Uses `macos-latest` and requires a GitHub token.
#     - **Key Steps:**
#       - **Checkout Test Repository:** Retrieves code from the test repository.
#       - **Download Artifact:** Downloads the build artifact from a specified run ID.
#       - **Set Permissions:** Adjusts permissions for scripts to ensure executability.
#       - **Run Automated Installation:** Executes installation scripts.
#       - **Dependency Handling:** Installs necessary node modules.
#       - **Smoke Tests Execution:** Runs basic tests to ensure application stability.
#       - **Git Tag Verification:** Confirms the non-existence of the Git tag to prevent duplicates.
#       - **Release Management:** Creates or updates a release based on tag existence.
#       - **Artifact Handling:**
#         - Finds `.dmg` file for the release.
#         - Uploads `.dmg` to the GitHub release using the `gh` CLI.
#       - **Confirmation:** Prints a message confirming successful release creation and upload.
#
# This workflow facilitates the creation and publication of software releases, ensuring that the release process is automated, reliable, and easy to execute.

name: Production Release Stage

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: "Tag name for the release (e.g., v1.0.0)"
        required: true
        type: string
      run_id:
        description: "The id of the workflow run where the desired download artifact was uploaded from."
        required: true
        type: number

permissions: write-all

jobs:
  checks:
    name: Checks before release
    uses: ./.github/workflows/ReusableStage.yml
    with:
      tag_name: ${{ github.event.inputs.tag_name }}
      run_id: ${{ github.event.inputs.run_id }}
    secrets: inherit

  production:
    name: Production Release Stage
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: macos-latest
    needs: [checks]
    steps:
      - name: Restore Artifacts
        uses: actions/cache/restore@v4
        with:
          path: ./MongoDB Query Executor
          key: ${{ runner.os }}-cache-artifact-${{ github.event.inputs.run_id }}

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Create or Update Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG_NAME="${{ github.event.inputs.tag_name }}"
          RELEASE_NAME="Release ${TAG_NAME}"
          BODY="Automatic release for tag ${TAG_NAME}"

          # Check if release exists for the tag
          if gh release view "$TAG_NAME" > /dev/null 2>&1; then
            echo "Release $TAG_NAME exists. Updating..."
            gh release edit "$TAG_NAME" --title "$RELEASE_NAME" --notes "$BODY"
          else
            echo "Creating release $TAG_NAME"
            gh release create "$TAG_NAME" --title "$RELEASE_NAME" --notes "$BODY"
          fi

      - name: Find .dmg File
        id: find_dmg
        run: |
          DMG_PATH=$(find . -type f -name "*.dmg" | head -n 1)
          if [ -z "$DMG_PATH" ]; then
            echo "Error: .dmg file not found!"
            exit 1
          fi
          echo "dmg_path=$DMG_PATH" >> $GITHUB_OUTPUT

      - name: Upload .dmg to Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG_NAME="${{ github.event.inputs.tag_name }}"
          DMG_PATH="${{ steps.find_dmg.outputs.dmg_path }}"

          echo "Uploading $DMG_PATH to release $TAG_NAME"
          gh release upload "$TAG_NAME" "$DMG_PATH" --clobber

      - name: Confirm Upload
        if: success()
        run: echo "Release created and .dmg uploaded successfully."

  production_stage_badge:
    name: Create status badge for workflow
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: [production]
    steps:
      - name: Production Stage badge (Success)
        if: ${{ !contains(needs.*.result, 'failure') }}
        uses: RubbaBoy/BYOB@v1.3.0
        with:
          NAME: production_stage
          LABEL: "Production Stage"
          STATUS: "Success"
          COLOR: green
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Production Stage badge (Failure)
        if: ${{ contains(needs.*.result, 'failure') }}
        uses: RubbaBoy/BYOB@v1.3.0
        with:
          NAME: production_stage
          LABEL: "Production Stage"
          STATUS: "Failure"
          COLOR: red
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
